"""
Demand Forecasting API endpoints (PDF Module 4).

Serves PRE-COMPUTED forecasts from the database (generated by
train_demand_forecasting.py), rather than running Prophet live on every
request -- matches how real forecasting systems work: forecasts are
generated periodically (e.g. nightly batch jobs), then served instantly
from storage. Re-running a model on every API call would be slow and
wasteful when the underlying sales history hasn't changed since the
last training run.
"""

from fastapi import APIRouter, HTTPException, Depends
from sqlalchemy.orm import Session

from app.core.database import get_db
from app.models.models import Product, DemandForecast
from app.schemas.forecasting import ProductForecastResponse, DemandForecastItem

router = APIRouter(prefix="/api/forecasting", tags=["Forecasting"])


@router.get("/products", response_model=list[dict])
def list_forecasted_products(db: Session = Depends(get_db)):
    """
    Lists every product that currently has at least one saved forecast --
    lets the frontend show a picker instead of guessing valid product IDs.
    """
    product_ids = db.query(DemandForecast.product_id).distinct().all()
    ids = [p[0] for p in product_ids]
    products = db.query(Product).filter(Product.id.in_(ids)).all()
    return [{"product_id": p.id, "name": p.name} for p in products]


@router.get("/{product_id}", response_model=ProductForecastResponse)
def get_product_forecast(product_id: int, db: Session = Depends(get_db)):
    product = db.query(Product).filter(Product.id == product_id).first()
    if not product:
        raise HTTPException(status_code=404, detail=f"Product {product_id} not found")

    forecasts = (
        db.query(DemandForecast)
        .filter(DemandForecast.product_id == product_id)
        .order_by(DemandForecast.generated_at.desc())
        .all()
    )
    if not forecasts:
        raise HTTPException(
            status_code=404,
            detail=f"No forecasts found for product {product_id}. "
                   "Run `python -m app.ml.train_demand_forecasting` first.",
        )

    return ProductForecastResponse(
        product_id=product.id,
        product_name=product.name,
        forecasts=[DemandForecastItem.model_validate(f) for f in forecasts],
    )