import streamlit as st
import joblib
import pandas as pd
import numpy as np 
from dotenv import load_dotenv
import os

load_dotenv()

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
st.set_page_config(
    page_title="PricePilot AI",
    page_icon="💰",
    layout="wide"
)

from openai import OpenAI

client = OpenAI(api_key=OPENAI_API_KEY)

def generate_ai_insight(
    current_price,
    recommended_price,
    predicted_demand,
    expected_revenue,
    competitor_price
):
    prompt = f"""
You are an AI pricing intelligence assistant for an e-commerce system.

Analyze these pricing results generated by the machine learning model:

Current Price: ₹{current_price:.2f}
Recommended Price: ₹{recommended_price:.2f}
Competitor Price: ₹{competitor_price:.2f}
Predicted Demand: {predicted_demand:.0f} units
Expected Revenue: ₹{expected_revenue:.2f}

Give a concise business insight in 2-3 sentences.

Your explanation should:
1. State whether the recommended price is higher or lower than the current price.
2. Compare the recommended price with the competitor price.
3. Explain that the recommendation is based on predicted demand and expected revenue.
4. Clearly state that the recommendation does not guarantee actual revenue.

Do not invent additional data or make claims about customer behavior that are not provided.
"""

    response = client.responses.create(
        model="gpt-5.6-luna",
        input=prompt
    )

    return response.output_text

# Load trained pricing model
pricing_model = joblib.load("pricepilot_xgb_model.pkl")

# Load trained demand forecasting model
forecast_model = joblib.load(
    "pricepilot_demand_forecast_model.pkl"
)

# Load demand forecast results
monthly_demand = pd.read_csv(
    "pricepilot_forecast_results.csv"
)
monthly_demand["Demand_Trend"] = (
    monthly_demand["Predicted Demand"].pct_change() * 100
)

monthly_demand["Trend Classification"] = (
    monthly_demand["Demand_Trend"]
    .fillna(0)
    .apply(
        lambda x:
        "Increasing" if x > 5
        else "Decreasing" if x < -5
        else "Stable"
    )
)
# Load preprocessing pipeline
preprocessor = joblib.load("pricepilot_preprocessor.pkl")


# -----------------------------
# Header
# -----------------------------
st.title("💰 PricePilot AI")
st.subheader("Dynamic Pricing & Revenue Intelligence")
st.write(
    "PricePilot AI uses machine learning to predict demand, "
    "optimize product prices, forecast future demand, and provide "
    "AI-generated pricing insights."
)
input_date = st.date_input(
    "Pricing Date"
)
st.markdown("---")

st.markdown("---")

st.info(
    "🔄 Workflow: Input Data → XGBoost Demand Prediction → "
    "Price Optimization → Revenue Estimation → LLM Pricing Insight"
)
# -----------------------------
# Pricing Inputs
# -----------------------------
st.header("📦 Product Pricing Inputs")
st.caption(
    "Enter product, market, and pricing conditions to generate an AI-based price recommendation."
)
col1, col2, col3 = st.columns(3)

with col1:
    category = st.selectbox(
        "Category",
        [
            "Books",
            "Electronics",
            "Fashion",
            "Beauty",
            "Grocery",
            "Home & Kitchen",
            "Sports",
            "Toys"
        ]
    )

    region = st.selectbox(
        "Region",
        ["North", "South", "East", "West", "Central"]
    )

    sales_channel = st.selectbox(
        "Sales Channel",
        ["Website", "Mobile App", "Marketplace"]
    )

with col2:
    current_price = st.number_input(
        "Current Price (₹)",
        min_value=1.0,
        value=50.0
    )

    competitor_price = st.number_input(
        "Competitor Price (₹)",
        min_value=1.0,
        value=40.0
    )

    discount = st.slider(
        "Discount Percentage",
        min_value=0,
        max_value=30,
        value=10
    )

with col3:
    marketing_spend = st.number_input(
        "Marketing Spend",
        min_value=0.0,
        value=500.0
    )

    website_visits = st.number_input(
        "Website Visits",
        min_value=0,
        value=1000
    )

    search_interest = st.number_input(
        "Search Interest",
        min_value=0.0,
        value=40.0
    )

    stock_availability = st.slider(
        "Stock Availability (%)",
        min_value=0.0,
        max_value=100.0,
        value=80.0
    )
st.markdown("---")
st.subheader("📊 Additional Market & Product Conditions")

col4, col5, col6 = st.columns(3)

with col4:
    customer_rating = st.slider(
        "Customer Rating",
        min_value=1.0,
        max_value=5.0,
        value=4.0,
        step=0.1
    )

    return_rate = st.slider(
        "Return Rate (%)",
        min_value=0.0,
        max_value=100.0,
        value=5.0
    )

with col5:
    holiday_flag = st.selectbox(
        "Holiday",
        ["No", "Yes"]
    )

    promotion_flag = st.selectbox(
        "Promotion",
        ["No", "Yes"]
    )

    new_product_flag = st.selectbox(
        "New Product",
        ["No", "Yes"]
    )

with col6:
    delivery_days = st.number_input(
        "Delivery Days",
        min_value=1,
        max_value=30,
        value=3
    )

st.markdown("---")


if st.button("🚀 Calculate Recommended Price"):

    # Calculate price-related features
    price_difference = current_price - competitor_price
    price_ratio = current_price / competitor_price

    if current_price < competitor_price:
        price_position = "Cheaper"
    else:
        price_position = "More Expensive"

    # Create input row in the same structure used during training
    input_data = {
        "Category": category,
        "Region": region,
        "Sales_Channel": sales_channel,
        "Price": current_price,
        "Discount_Percentage": discount,
        "Marketing_Spend": marketing_spend,
        "Website_Visits": website_visits,
        "Search_Interest": search_interest,
        "Competitor_Price": competitor_price,
        "Stock_Availability": stock_availability,
        "Customer_Rating": customer_rating,
        "Return_Rate": return_rate,
        "Holiday_Flag": 1 if holiday_flag == "Yes" else 0,
        "Promotion_Flag": 1 if promotion_flag == "Yes" else 0,
        "New_Product_Flag": 1 if new_product_flag == "Yes" else 0,
        "Delivery_Days": delivery_days,
        "Month": input_date.month,
        "Season": (
            "Winter" if input_date.month in [12, 1, 2]
            else "Spring" if input_date.month in [3, 4, 5]
            else "Summer" if input_date.month in [6, 7, 8]
            else "Autumn"
        ),
        "Year": input_date.year,
        "Quarter": ((input_date.month - 1) // 3) + 1,
        "DayOfWeek": input_date.weekday(),
        "Price_Difference": price_difference,
        "Price_Ratio": price_ratio,
        "Price_Position": price_position,
    }

    input_df = pd.DataFrame([input_data])

    # Apply preprocessing
    processed_input = preprocessor.transform(input_df)

    # Predict demand at current price
    predicted_demand = pricing_model.predict(
        processed_input
    )[0]
    st.subheader("📊 Current Price Demand Prediction")

    st.metric(
        "Predicted Demand at Current Price",
        f"{predicted_demand:.0f} units"
    )

    # Generate candidate prices
    min_price = competitor_price * 0.80
    max_price = competitor_price * 1.20

    candidate_prices = np.linspace(
        min_price,
        max_price,
        9
    )

    pricing_results = []

    for candidate_price in candidate_prices:

        scenario = input_data.copy()

        scenario["Price"] = candidate_price
        scenario["Price_Difference"] = (
            candidate_price - competitor_price
        )
        scenario["Price_Ratio"] = (
            candidate_price / competitor_price
        )

        if candidate_price < competitor_price:
            scenario["Price_Position"] = "Cheaper"
        else:
            scenario["Price_Position"] = "More Expensive"

        scenario_df = pd.DataFrame([scenario])

        scenario_processed = preprocessor.transform(
            scenario_df
        )

        scenario_demand = pricing_model.predict(
            scenario_processed
        )[0]

        # Revenue formula used by the dataset
        scenario_revenue = (
            candidate_price
            * scenario_demand
            * (1 - discount / 100)
        )

        pricing_results.append({
            "Candidate Price": candidate_price,
            "Predicted Demand": scenario_demand,
            "Expected Revenue": scenario_revenue
        })

    pricing_results_df = pd.DataFrame(
        pricing_results
    )

    # Select price with maximum expected revenue
    best_row = pricing_results_df.loc[
        pricing_results_df["Expected Revenue"].idxmax()
    ]

    recommended_price = best_row["Candidate Price"]
    recommended_demand = best_row["Predicted Demand"]
    recommended_revenue = best_row["Expected Revenue"]
    price_change = recommended_price - current_price
    price_change_percentage = (
        price_change / current_price
    ) * 100
    # Display recommendation
    st.markdown("---")
    st.header("🎯 Recommended Pricing")

    col1, col2, col3 = st.columns(3)

    with col1:
        st.metric(
            "Recommended Price",
            f"₹{recommended_price:.2f}"
        )

    with col2:
        st.metric(
            "Predicted Demand",
            f"{recommended_demand:.0f} units"
        )

    with col3:
        st.metric(
            "Expected Revenue",
            f"₹{recommended_revenue:.2f}"
        )
    st.info(
        f"Current Price: ₹{current_price:.2f} → "
        f"Recommended Price: ₹{recommended_price:.2f} "
        f"({price_change_percentage:+.1f}%)"
    )
    st.caption(
        f"Price range considered: "
        f"₹{min_price:.2f} – ₹{max_price:.2f}"
    )
    st.caption(
    "Recommendation is based on predicted demand and expected revenue "
    "within the selected competitor-price range."
    )
    st.caption(
    "⚠️ This is a model-based recommendation for decision support. "
    "Actual demand and revenue may differ from predictions."
)
    st.markdown("---")
    st.subheader("🤖 AI Pricing Insight")

    ai_insight = generate_ai_insight(
        current_price,
        recommended_price,
        recommended_demand,
        recommended_revenue,
        competitor_price
    )

    st.info(ai_insight)

    st.markdown("---")
    st.subheader("📈 Price vs Expected Revenue")

    chart_data = pricing_results_df[
        ["Candidate Price", "Expected Revenue"]
    ].copy()

    chart_data = chart_data.set_index(
        "Candidate Price"
    )

    st.line_chart(chart_data)

st.markdown("---")
st.subheader("🤖 Model Information")

col1, col2 = st.columns(2)

with col1:
    st.write("**Pricing Model:** XGBoost Regressor")

with col2:
    st.write("**Demand Forecasting:** XGBoost Regressor")


st.header("📊 Forecast Summary")
st.caption(
    "Forecast results shown here are based on the 2025 holdout period. "
    "Confidence score is a project-level indicator derived from forecast error."
)
st.info(
    "Note: Forecast confidence is a project-level indicator based on historical "
    "forecast error and should not be interpreted as a probability."
)
col1, col2, col3 = st.columns(3)

with col1:
    st.metric(
        "Average Predicted Demand",
        f"{monthly_demand['Predicted Demand'].mean():.0f} units"
    )

with col2:
    highest_month = monthly_demand.loc[
        monthly_demand["Predicted Demand"].idxmax(),
        "Month"
    ]

    st.metric(
        "Highest Demand Month",
        highest_month
    )

with col3:
    increasing_months = (
        monthly_demand["Trend Classification"] == "Increasing"
    ).sum()

    st.metric(
        "Increasing-Demand Months",
        f"{increasing_months} months"
    )
st.subheader("📈 Predicted Demand by Month")

forecast_chart = monthly_demand[
    ["Month", "Predicted Demand"]
].copy()

forecast_chart = forecast_chart.set_index("Month")

st.line_chart(
    forecast_chart
)
st.markdown("---")
st.header("📈 Demand Forecast")
st.caption(
    "Monthly demand forecasts with forecast horizon, confidence score, and demand trend classification."
)
forecast_display = monthly_demand[
    [
        "Month",
        "Predicted Demand",
        "Forecast Horizon",
        "Confidence Score",
        "Trend Classification"
    ]
].copy()

st.dataframe(
    forecast_display,
    use_container_width=True,
    hide_index=True
)