import React, { useState } from "react";
import { 
  FileText, 
  Download, 
  Printer, 
  TrendingUp, 
  ShoppingBag, 
  DollarSign, 
  Crosshair, 
  Calendar, 
  CheckCircle2,
  BarChart3,
  Layers
} from "lucide-react";
import { DEMAND_FORECAST_SERIES, CATEGORY_REVENUE_DATA } from "../../data/intelligenceData";

function ReportsTab({ products = [], dashboardData, user }) {
  const currentDate = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const totalProducts = products.length;
  const totalStock = products.reduce((acc, p) => acc + Number(p.stock_availability || 0), 0);
  const avgCurrentPrice = totalProducts > 0 
    ? (products.reduce((acc, p) => acc + Number(p.current_price || 0), 0) / totalProducts).toFixed(2)
    : "0.00";
  const avgCompetitorPrice = totalProducts > 0 
    ? (products.reduce((acc, p) => acc + Number(p.competitor_price || 0), 0) / totalProducts).toFixed(2)
    : "0.00";

  const cheaperCount = products.filter(p => Number(p.current_price) < Number(p.competitor_price)).length;
  const expensiveCount = products.filter(p => Number(p.current_price) > Number(p.competitor_price)).length;
  const parityCount = products.filter(p => Number(p.current_price) === Number(p.competitor_price)).length;

  // Generate and Download CSV with actual live database records
  const handleDownloadCSV = () => {
    let csv = `PricePilot AI - Executive Pricing & Portfolio Intelligence Report\n`;
    csv += `Generated Date: ${new Date().toISOString()}\n`;
    csv += `Generated By: ${user?.username || "Admin"} (${user?.role || "ADMIN"})\n\n`;
    
    csv += `EXECUTIVE SUMMARY METRICS\n`;
    csv += `Total Products,${totalProducts}\n`;
    csv += `Total Stock Units,${totalStock}\n`;
    csv += `Average Selling Price,₹${avgCurrentPrice}\n`;
    csv += `Average Competitor Price,₹${avgCompetitorPrice}\n`;
    csv += `Cheaper Than Competitors,${cheaperCount}\n`;
    csv += `More Expensive Than Competitors,${expensiveCount}\n\n`;

    csv += `PRODUCT LEVEL PRICING & MARKET BENCHMARKS\n`;
    csv += `ID,Product Name,Category,Region,Our Price (₹),Competitor Price (₹),Price Difference (₹),Price Ratio,Position Status,Stock\n`;

    products.forEach((p) => {
      const diff = Number(p.current_price) - Number(p.competitor_price);
      const ratio = p.competitor_price > 0 ? (Number(p.current_price) / Number(p.competitor_price)).toFixed(2) : "1.00";
      const status = diff < 0 ? "Below Competitor" : diff > 0 ? "Above Competitor" : "At Parity";
      csv += `"${p.id}","${p.product_name}","${p.category}","${p.region}",${Number(p.current_price).toFixed(2)},${Number(p.competitor_price).toFixed(2)},${diff.toFixed(2)},${ratio},"${status}",${p.stock_availability}\n`;
    });

    csv += `\nDEMAND FORECASTING SUMMARY (NEXT 12 MONTHS)\n`;
    csv += `Month,Forecast Horizon,Predicted Demand (Units),Confidence Score\n`;
    DEMAND_FORECAST_SERIES.forEach((d) => {
      csv += `"${d.month}","${d.horizon}",${d.demand},${d.confidence}%\n`;
    });

    const blob = new Blob([csv], { type: "text/csv;charset=utf-8;" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.setAttribute("download", `PricePilot_AI_Report_${new Date().toISOString().slice(0, 10)}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  // Trigger Print / PDF generation
  const handlePrintPDF = () => {
    window.print();
  };

  return (
    <div className="reports-page-wrapper">
      {/* Top action header */}
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "24px", flexWrap: "wrap", gap: "16px" }}>
        <div>
          <h2 style={{ fontSize: 24, fontWeight: 800 }}>Comprehensive Pricing & Intelligence Reports</h2>
          <p style={{ fontSize: 13, color: "var(--text-secondary)" }}>
            Full portfolio audit, competitor comparison differentials, and forecasted demand telemetry.
          </p>
        </div>

        <div style={{ display: "flex", gap: "12px" }}>
          <button className="btn btn-secondary btn-sm" onClick={handlePrintPDF}>
            <Printer size={15} />
            Print / Save PDF
          </button>
          <button className="btn btn-primary btn-sm" onClick={handleDownloadCSV}>
            <Download size={15} />
            Export Live CSV Report
          </button>
        </div>
      </div>

      {/* Report Header Card */}
      <div className="glass-panel" style={{ padding: "28px", marginBottom: "24px", borderLeft: "4px solid var(--accent-emerald)" }}>
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", flexWrap: "wrap", gap: "16px" }}>
          <div>
            <div className="badge-glow" style={{ marginBottom: "8px" }}>
              <FileText size={13} />
              <span>Official Executive Briefing</span>
            </div>
            <h3 style={{ fontSize: 22, fontWeight: 800 }}>PricePilot AI Business & Pricing Report</h3>
            <p style={{ fontSize: 13, color: "var(--text-secondary)", marginTop: 4 }}>
              Generated on {currentDate} | Evaluator: <strong>{user?.username || "Admin"}</strong> ({user?.role || "ADMIN"})
            </p>
          </div>

          <div style={{ textAlign: "right" }}>
            <div style={{ fontSize: 12, color: "var(--text-muted)" }}>SYSTEM REPORT ID</div>
            <code style={{ fontSize: 14, color: "var(--accent-cyan)", fontWeight: 700 }}>PP-RPT-{Date.now().toString().slice(-6)}</code>
          </div>
        </div>
      </div>

      {/* Summary KPI Cards */}
      <div className="metrics-grid" style={{ marginBottom: "28px" }}>
        <div className="metric-card">
          <div>
            <div className="metric-label">Total Active Products</div>
            <div className="metric-value">{totalProducts}</div>
            <div className="metric-trend trend-up">
              <span>{totalStock.toLocaleString()} total units in stock</span>
            </div>
          </div>
          <div className="metric-icon-wrap" style={{ color: "#10b981", background: "rgba(16, 185, 129, 0.12)" }}>
            <ShoppingBag size={22} />
          </div>
        </div>

        <div className="metric-card">
          <div>
            <div className="metric-label">Avg Selling Price</div>
            <div className="metric-value">₹{avgCurrentPrice}</div>
            <div className="metric-trend trend-neutral">
              <span>Competitor Avg: ₹{avgCompetitorPrice}</span>
            </div>
          </div>
          <div className="metric-icon-wrap" style={{ color: "#38bdf8", background: "rgba(56, 189, 248, 0.12)" }}>
            <DollarSign size={22} />
          </div>
        </div>

        <div className="metric-card">
          <div>
            <div className="metric-label">Cheaper Than Market</div>
            <div className="metric-value" style={{ color: "#10b981" }}>{cheaperCount}</div>
            <div className="metric-trend trend-up">
              <span>Competitive pricing advantage</span>
            </div>
          </div>
          <div className="metric-icon-wrap" style={{ color: "#10b981", background: "rgba(16, 185, 129, 0.12)" }}>
            <TrendingUp size={22} />
          </div>
        </div>

        <div className="metric-card">
          <div>
            <div className="metric-label">Priced at Premium</div>
            <div className="metric-value" style={{ color: "#f59e0b" }}>{expensiveCount}</div>
            <div className="metric-trend trend-down">
              <span>{parityCount} SKUs at price parity</span>
            </div>
          </div>
          <div className="metric-icon-wrap" style={{ color: "#f59e0b", background: "rgba(245, 158, 11, 0.12)" }}>
            <Crosshair size={22} />
          </div>
        </div>
      </div>

      {/* Live Product Pricing Summary Table */}
      <div className="table-container" style={{ marginBottom: "28px" }}>
        <div className="table-header-bar">
          <h3 style={{ fontSize: 16, fontWeight: 700 }}>Database Product Pricing & Competitor Differentials</h3>
          <span className="tag-badge active">{totalProducts} Verified Records</span>
        </div>

        <table className="custom-table">
          <thead>
            <tr>
              <th>Product Name</th>
              <th>Category</th>
              <th>Region</th>
              <th>Our Price</th>
              <th>Competitor</th>
              <th>Difference (₹)</th>
              <th>Ratio</th>
              <th>Stock Status</th>
            </tr>
          </thead>
          <tbody>
            {products.length === 0 ? (
              <tr>
                <td colSpan={8} style={{ textAlign: "center", padding: "30px", color: "var(--text-muted)" }}>
                  No product data found in database.
                </td>
              </tr>
            ) : (
              products.map((p) => {
                const diff = Number(p.current_price) - Number(p.competitor_price);
                const ratio = p.competitor_price > 0 ? (Number(p.current_price) / Number(p.competitor_price)).toFixed(2) : "1.00";
                const isCheaper = diff < 0;

                return (
                  <tr key={p.id}>
                    <td>
                      <strong>{p.product_name}</strong>
                    </td>
                    <td><span className="tag-badge">{p.category}</span></td>
                    <td>{p.region}</td>
                    <td><strong style={{ color: "var(--accent-emerald)" }}>₹{Number(p.current_price).toFixed(2)}</strong></td>
                    <td style={{ color: "var(--text-muted)" }}>₹{Number(p.competitor_price).toFixed(2)}</td>
                    <td>
                      <span className={`tag-badge ${isCheaper ? 'active' : ''}`}>
                        {isCheaper ? `-₹${Math.abs(diff).toFixed(2)}` : `+₹${diff.toFixed(2)}`}
                      </span>
                    </td>
                    <td>{ratio}x</td>
                    <td>
                      <span className={`stock-tag ${p.stock_availability > 50 ? 'stock-in' : p.stock_availability > 0 ? 'stock-low' : 'stock-out'}`}>
                        {p.stock_availability} units
                      </span>
                    </td>
                  </tr>
                );
              })
            )}
          </tbody>
        </table>
      </div>

      {/* Demand Forecasting Summary Table in Report */}
      <div className="table-container">
        <div className="table-header-bar">
          <h3 style={{ fontSize: 16, fontWeight: 700 }}>12-Month Demand Forecast Horizon Telemetry</h3>
          <span className="badge-glow">Model Validated Projections</span>
        </div>

        <table className="custom-table">
          <thead>
            <tr>
              <th>Forecast Month</th>
              <th>Horizon Scope</th>
              <th>Predicted Volume</th>
              <th>Trend Rate</th>
              <th>Model Confidence</th>
            </tr>
          </thead>
          <tbody>
            {DEMAND_FORECAST_SERIES.slice(0, 6).map((d, i) => (
              <tr key={i}>
                <td><strong>{d.month}</strong></td>
                <td><span className="tag-badge">{d.horizon}</span></td>
                <td><strong style={{ color: "var(--accent-emerald)" }}>{d.demand.toLocaleString()} units</strong></td>
                <td>{d.trend}</td>
                <td>{d.confidence}%</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}

export default ReportsTab;
