'use client';

import React, { useState, useEffect } from 'react';
import { api } from '@/lib/api';
import { RevenueResponse } from '@/lib/types';
import { SkuSelector } from '@/components/SkuSelector';
import { MetricCard } from '@/components/MetricCard';
import { ErrorBanner, LoadingSkeleton } from '@/components/ErrorBanner';
import {
  DollarSign,
  TrendingUp,
  Tag,
  Sparkles,
  Info,
  Layers,
  ArrowRight,
  ShieldCheck,
  CheckCircle2,
  HelpCircle,
} from 'lucide-react';
import {
  ResponsiveContainer,
  LineChart,
  Line,
  XAxis,
  YAxis,
  Tooltip,
  Legend,
  CartesianGrid,
  ReferenceDot,
} from 'recharts';

export default function RevenuePage() {
  const [itemId, setItemId] = useState('293375605257');
  const [storeId, setStoreId] = useState(1);

  const [data, setData] = useState<RevenueResponse | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const fetchRevenue = async (sku = itemId, store = storeId) => {
    setLoading(true);
    setError(null);
    try {
      const response = await api.getRevenueOptimization({
        item_id: sku,
        store_id: store,
      });
      setData(response);
      setItemId(sku);
      setStoreId(store);
    } catch (err: any) {
      setError(err.message || 'Failed to fetch revenue optimization data.');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchRevenue(itemId, storeId);
  }, []);

  const formatCurrency = (val?: number) =>
    val !== undefined ? `$${val.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}` : '$0.00';

  // Curve data for Price vs Expected Revenue
  const chartData = data?.candidates_summary.map((item) => ({
    price: item.candidate_price,
    expectedRevenue: item.expected_daily_revenue,
    predictedDemand: item.predicted_daily_demand,
    isOptimal: item.is_revenue_optimal,
    isClearing: item.is_clearing_recommended,
  })) || [];

  return (
    <div>
      {/* Header */}
      <div className="page-header">
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: '12px' }}>
          <div>
            <h1 className="page-title">
              <DollarSign size={28} color="var(--accent-emerald)" />
              Gross Revenue Optimization & Elasticity
            </h1>
            <p className="page-subtitle">
              Simulates coupled demand elasticity to isolate the revenue-maximizing price point vs clearing baseline.
            </p>
          </div>

          <div style={{ display: 'flex', gap: '8px' }}>
            <span className="badge badge-emerald">
              Empirical Price Elasticity Engine
            </span>
            {data?._dataSource === 'MOCK_FALLBACK' || error || !data ? (
              <span className="badge badge-amber">DEMO / MOCK DATA</span>
            ) : (
              <span className="badge badge-emerald">LIVE API (FastAPI)</span>
            )}
          </div>
        </div>
      </div>

      {/* Selector */}
      <SkuSelector
        itemId={itemId}
        storeId={storeId}
        onSearch={(sku, store) => fetchRevenue(sku, store)}
        isLoading={loading}
      />

      {error && <ErrorBanner message={error} onRetry={() => fetchRevenue(itemId, storeId)} />}

      {/* Mandatory Disclaimer Alert */}
      <div className="alert-banner alert-banner-info">
        <Info size={18} color="#10b981" style={{ flexShrink: 0, marginTop: '2px' }} />
        <div style={{ fontSize: '0.825rem', lineHeight: 1.5 }}>
          <strong>Revenue vs Profit Scope:</strong> Revenue optimization is based strictly on modeled gross revenue generated by price times predicted demand. Profit optimization requires product cost / COGS data.
        </div>
      </div>

      {loading ? (
        <div>
          <div className="grid-4" style={{ marginBottom: '20px' }}>
            <LoadingSkeleton height={130} />
            <LoadingSkeleton height={130} />
            <LoadingSkeleton height={130} />
            <LoadingSkeleton height={130} />
          </div>
          <LoadingSkeleton height={320} />
        </div>
      ) : data ? (
        <div style={{ display: 'flex', flexDirection: 'column', gap: '24px' }}>
          {/* Top KPI Cards */}
          <div className="grid-4">
            <MetricCard
              label="Optimal Revenue Price"
              value={formatCurrency(data.optimal_revenue_price)}
              subtitle={`Delta: +${data.optimal_price_change_pct_from_ref}% vs Ref`}
              icon={DollarSign}
              accentColor="#10b981"
              badge={{ text: 'Revenue Vertex', variant: 'emerald' }}
              tooltip="Price point that maximizes total gross sales revenue"
            />

            <MetricCard
              label="Expected Daily Revenue"
              value={formatCurrency(data.optimal_expected_revenue)}
              subtitle={`Baseline Ref: ${formatCurrency(data.reference_expected_revenue)}`}
              icon={TrendingUp}
              accentColor="#06b6d4"
              trend={{
                value: `+${data.optimal_revenue_lift_pct_vs_ref}%`,
                direction: 'up',
              }}
            />

            <MetricCard
              label="Predicted Daily Demand"
              value={`${data.optimal_expected_demand.toFixed(1)} u/d`}
              subtitle={`At clearing: ${data.clearing_expected_demand.toFixed(1)} u/d`}
              icon={Tag}
              accentColor="#818cf8"
              badge={{
                text: `${data.optimal_demand_change_pct_vs_ref}% Vol Delta`,
                variant: 'indigo',
              }}
            />

            <MetricCard
              label="Clearing Rec Price"
              value={formatCurrency(data.clearing_recommended_price)}
              subtitle={`Predicted Clearing: ${formatCurrency(data.predicted_clearing_price)}`}
              icon={Sparkles}
              accentColor="#f59e0b"
              badge={{ text: 'Clearing Engine', variant: 'amber' }}
            />
          </div>

          {/* Main Visualization: Price vs Expected Revenue Elasticity Curve */}
          <div className="card">
            <div className="card-header">
              <div>
                <div className="card-title">
                  <DollarSign size={18} color="var(--accent-emerald)" />
                  Price vs Expected Daily Revenue Curve
                </div>
                <div className="card-desc">
                  Simulated gross daily revenue across the candidate price grid (Elasticity Model)
                </div>
              </div>
              <span className="badge badge-emerald">
                Revenue Optimal: {formatCurrency(data.optimal_revenue_price)} (+{data.optimal_revenue_lift_pct_vs_ref}% Lift)
              </span>
            </div>

            <div style={{ height: '280px', width: '100%' }}>
              <ResponsiveContainer width="100%" height="100%">
                <LineChart data={chartData} margin={{ left: 10, right: 20, top: 10, bottom: 10 }}>
                  <CartesianGrid strokeDasharray="3 3" stroke="#334155" />
                  <XAxis dataKey="price" stroke="#64748b" tickFormatter={(v) => `$${v}`} tick={{ fontSize: 11 }} />
                  <YAxis stroke="#64748b" tickFormatter={(v) => `$${v}`} />
                  <Tooltip contentStyle={{ backgroundColor: '#1e293b', borderColor: '#475569', borderRadius: '8px' }} />
                  <Legend />
                  <Line
                    type="monotone"
                    dataKey="expectedRevenue"
                    name="Expected Daily Revenue ($)"
                    stroke="#10b981"
                    strokeWidth={3}
                    dot={{ r: 4 }}
                    activeDot={{ r: 7 }}
                  />
                  <Line
                    type="monotone"
                    dataKey="predictedDemand"
                    name="Predicted Daily Demand (Units)"
                    stroke="#06b6d4"
                    strokeWidth={2}
                    strokeDasharray="4 4"
                  />
                </LineChart>
              </ResponsiveContainer>
            </div>

            <div style={{ fontSize: '0.8rem', color: 'var(--text-muted)', marginTop: '8px', borderTop: '1px solid rgba(51,65,85,0.4)', paddingTop: '8px' }}>
              <strong>Optimization Rationale:</strong> {data.optimization_rationale}
            </div>
          </div>

          {/* Pricing Scenario Comparison Table */}
          <div className="card">
            <div className="card-header">
              <div className="card-title">
                <Layers size={18} color="var(--accent-cyan)" />
                Pricing Scenario Comparison
              </div>
              <span className="badge badge-cyan">3 Modeled Strategies</span>
            </div>

            <div className="table-container">
              <table className="table">
                <thead>
                  <tr>
                    <th>Scenario</th>
                    <th>Price Point</th>
                    <th>Predicted Daily Demand</th>
                    <th>Expected Daily Revenue</th>
                    <th>Revenue Lift vs Ref</th>
                    <th>Strategic Role</th>
                  </tr>
                </thead>
                <tbody>
                  {/* Scenario 1: Reference */}
                  <tr>
                    <td>
                      <div style={{ fontWeight: 600, color: 'var(--text-primary)' }}>Reference Baseline</div>
                      <div style={{ fontSize: '0.75rem', color: 'var(--text-muted)' }}>Observed POS Shelf Price</div>
                    </td>
                    <td style={{ fontWeight: 700, color: 'var(--text-primary)' }}>
                      {formatCurrency(data.reference_price)}
                    </td>
                    <td style={{ color: 'var(--text-secondary)' }}>
                      {data.reference_expected_demand.toFixed(1)} units/day
                    </td>
                    <td style={{ color: 'var(--text-secondary)' }}>
                      {formatCurrency(data.reference_expected_revenue)}
                    </td>
                    <td>
                      <span className="badge badge-gray">Baseline (0.0%)</span>
                    </td>
                    <td style={{ fontSize: '0.8rem', color: 'var(--text-muted)' }}>Current Status Quo</td>
                  </tr>

                  {/* Scenario 2: Clearing Recommendation */}
                  <tr>
                    <td>
                      <div style={{ fontWeight: 600, color: 'var(--pastel-amber-text)' }}>Current / Clearing Recommendation</div>
                      <div style={{ fontSize: '0.75rem', color: 'var(--text-muted)' }}>Market Clearing Model</div>
                    </td>
                    <td style={{ fontWeight: 700, color: '#f59e0b' }}>
                      {formatCurrency(data.clearing_recommended_price)}
                    </td>
                    <td style={{ color: 'var(--text-secondary)' }}>
                      {data.clearing_expected_demand.toFixed(1)} units/day
                    </td>
                    <td style={{ color: 'var(--text-secondary)' }}>
                      {formatCurrency(data.clearing_expected_revenue)}
                    </td>
                    <td>
                      <span className="badge badge-amber">
                        +{(((data.clearing_expected_revenue - data.reference_expected_revenue) / data.reference_expected_revenue) * 100).toFixed(1)}%
                      </span>
                    </td>
                    <td style={{ fontSize: '0.8rem', color: 'var(--text-muted)' }}>Balanced Velocity & Margin</td>
                  </tr>

                  {/* Scenario 3: Revenue Optimized */}
                  <tr style={{ backgroundColor: 'rgba(16, 185, 129, 0.12)' }}>
                    <td>
                      <div style={{ fontWeight: 700, color: 'var(--pastel-mint-text)' }}>Revenue Optimized (Recommended)</div>
                      <div style={{ fontSize: '0.75rem', color: '#a7f3d0' }}>Maximum Gross Revenue Peak</div>
                    </td>
                    <td style={{ fontWeight: 800, color: '#34d399', fontSize: '1rem' }}>
                      {formatCurrency(data.optimal_revenue_price)}
                    </td>
                    <td style={{ color: 'var(--text-primary)', fontWeight: 600 }}>
                      {data.optimal_expected_demand.toFixed(1)} units/day
                    </td>
                    <td style={{ color: 'var(--text-primary)', fontWeight: 700 }}>
                      {formatCurrency(data.optimal_expected_revenue)}
                    </td>
                    <td>
                      <span className="badge badge-emerald">
                        +{data.optimal_revenue_lift_pct_vs_ref}% Lift
                      </span>
                    </td>
                    <td style={{ fontSize: '0.8rem', color: '#a7f3d0', fontWeight: 600 }}>Maximum Gross Revenue</td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      ) : null}
    </div>
  );
}
