"""add lag_price qty customers product_score to price_history

Revision ID: 23eab9a974b4
Revises: 45134f8a8936
Create Date: 2026-08-26 11:30:29.814860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23eab9a974b4'
down_revision: Union[str, Sequence[str], None] = '45134f8a8936'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price_history', sa.Column('lag_price', sa.Float(), nullable=True))
    op.add_column('price_history', sa.Column('qty', sa.Integer(), nullable=True))
    op.add_column('price_history', sa.Column('customers', sa.Integer(), nullable=True))
    op.add_column('price_history', sa.Column('product_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('price_history', 'product_score')
    op.drop_column('price_history', 'customers')
    op.drop_column('price_history', 'qty')
    op.drop_column('price_history', 'lag_price')
    # ### end Alembic commands ###
