"""baseline_and_ml_columns

Revision ID: 30257bc31c7a
Revises: 
Create Date: 2026-08-27 13:23:08.388520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30257bc31c7a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price_history', sa.Column('lag_price', sa.Float(), nullable=True))
    op.add_column('price_history', sa.Column('qty', sa.Integer(), nullable=True))
    op.add_column('price_history', sa.Column('customers', sa.Integer(), nullable=True))
    op.add_column('price_history', sa.Column('product_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('price_history', 'product_score')
    op.drop_column('price_history', 'customers')
    op.drop_column('price_history', 'qty')
    op.drop_column('price_history', 'lag_price')
    # ### end Alembic commands ###
